<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Highlights.Cli</RootNamespace>
    <AssemblyName>highlights</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Highlights.Core\Highlights.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>


</Project>
