<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CliWrap" Version="3.10.5" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.12" />
    <PackageVersion Include="Spectre.Console" Version="0.57.2" />
    <PackageVersion Include="System.CommandLine" Version="2.0.12" />
    <PackageVersion Include="Whisper.net" Version="1.9.1" />
    <PackageVersion Include="Whisper.net.Runtime" Version="1.9.1" />
    <PackageVersion Include="Whisper.net.Runtime.Cuda" Version="1.9.1" />
  </ItemGroup>
</Project>
